"""SQLAlchemy ORM models for VMAN (Milestone 0 / Task 2).

This module declares the foundational tables that other milestones depend
on. New tables for users/sessions/hosts/jobs/recipes land in the
milestones that introduce them so each migration matches the code that
exercises the model.

Conventions:

- Every primary key is a string UUID generated by the application.
- Every timestamp is timezone-aware UTC (``DateTime(timezone=True)``).
- Encrypted payloads are stored as BLOBs -- the application never reads
  plaintext from the database.
- JSON-shaped columns are typed as JSON (SQLite stores as TEXT, Postgres
  as JSONB).
"""

from __future__ import annotations

import datetime as dt

from sqlalchemy import (
    JSON,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    LargeBinary,
    String,
    UniqueConstraint,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from vman.db.base import Base

# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #


def _utcnow() -> dt.datetime:
    """Timezone-aware UTC now -- never naive datetimes on the wire."""
    return dt.datetime.now(dt.timezone.utc)


# --------------------------------------------------------------------------- #
# Encryption key registry
# --------------------------------------------------------------------------- #


class EncryptionKey(Base):
    """Versioned record of every master key the vault has used.

    The actual key material is NEVER stored here -- it lives in
    ``Settings.master_key`` (env). This table is the index that lets us
    decrypt old payloads after rotation.
    """

    __tablename__ = "encryption_keys"

    id: Mapped[str] = mapped_column(String(64), primary_key=True)
    version: Mapped[int] = mapped_column(Integer, nullable=False, unique=True)
    # active | rotated | revoked
    status: Mapped[str] = mapped_column(String(16), nullable=False, default="active")
    created_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )
    rotated_at: Mapped[dt.datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    credentials: Mapped[list[Credential]] = relationship(back_populates="encryption_key")

    __table_args__ = (
        CheckConstraint(
            "status IN ('active', 'rotated', 'revoked')",
            name="ck_encryption_keys_status",
        ),
    )


# --------------------------------------------------------------------------- #
# Credential vault
# --------------------------------------------------------------------------- #


# The set of credential kinds we know how to use. Rejecting unknown kinds
# at the DB layer (not just Python) protects against typos creeping in
# via raw SQL or migrations.
CREDENTIAL_KINDS: frozenset[str] = frozenset(
    {
        "ssh_password",
        "ssh_private_key",
        "ssh_private_key_passphrase",
        "sudo_password",
        "api_token",
    }
)


class Credential(Base):
    """An encrypted credential (SSH password, SSH key, API token, ...).

    ``encrypted_payload`` is the ciphertext produced by ``Vault.encrypt``;
    it is always non-null, and the application never decrypts a credential
    outside the worker process.
    """

    __tablename__ = "credentials"

    id: Mapped[str] = mapped_column(String(64), primary_key=True)
    name: Mapped[str] = mapped_column(String(128), nullable=False, unique=True)
    kind: Mapped[str] = mapped_column(String(32), nullable=False)
    encrypted_payload: Mapped[bytes] = mapped_column(LargeBinary, nullable=False)
    encryption_key_id: Mapped[str] = mapped_column(
        String(64), ForeignKey("encryption_keys.id"), nullable=False
    )
    # Non-secret metadata: e.g. the SSH key fingerprint (sha256 of the
    # public half), the credential owner for display, etc.
    fingerprint: Mapped[str] = mapped_column(String(128), nullable=False, default="")
    metadata_json: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)
    last_used_at: Mapped[dt.datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    rotated_at: Mapped[dt.datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    disabled_at: Mapped[dt.datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )
    updated_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow, onupdate=_utcnow
    )

    encryption_key: Mapped[EncryptionKey] = relationship(back_populates="credentials")

    __table_args__ = (
        CheckConstraint(
            "kind IN ('ssh_password', 'ssh_private_key', "
            "'ssh_private_key_passphrase', 'sudo_password', 'api_token')",
            name="ck_credentials_kind",
        ),
        Index("ix_credentials_kind", "kind"),
    )


# --------------------------------------------------------------------------- #
# Audit
# --------------------------------------------------------------------------- #


# Actor types tell us where the action originated. MCP and CLI entries
# should be present alongside user-issued actions so a forensic review
# can answer "who did this, from where, on whose behalf?".
ACTOR_TYPES: frozenset[str] = frozenset({"user", "system", "mcp", "cli"})


class AuditEvent(Base):
    """Immutable audit record. Updated_at is omitted -- entries are append-only."""

    __tablename__ = "audit_events"

    id: Mapped[str] = mapped_column(String(64), primary_key=True)
    actor_user_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    actor_type: Mapped[str] = mapped_column(String(16), nullable=False)
    action: Mapped[str] = mapped_column(String(128), nullable=False)
    resource_type: Mapped[str] = mapped_column(String(64), nullable=False)
    resource_id: Mapped[str] = mapped_column(String(64), nullable=False, default="")
    ip_address: Mapped[str | None] = mapped_column(String(64), nullable=True)
    user_agent: Mapped[str | None] = mapped_column(String(512), nullable=True)
    metadata_json: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)
    previous_hash: Mapped[str] = mapped_column(String(64), nullable=False, default="")
    event_hash: Mapped[str] = mapped_column(String(64), nullable=False, default="")
    created_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow, index=True
    )

    __table_args__ = (
        CheckConstraint(
            "actor_type IN ('user', 'system', 'mcp', 'cli')",
            name="ck_audit_events_actor_type",
        ),
        Index("ix_audit_events_action", "action"),
        Index("ix_audit_events_resource", "resource_type", "resource_id"),
        Index("ix_audit_events_event_hash", "event_hash"),
    )


# --------------------------------------------------------------------------- #
# Users and authentication
# --------------------------------------------------------------------------- #


# User roles. owner is the bootstrap admin; admin can manage users + hosts;
# operator can run jobs; viewer is read-only.
USER_ROLES: frozenset[str] = frozenset({"owner", "admin", "operator", "viewer"})


class User(Base):
    """Local user account. Passwords are stored as Argon2id hashes."""

    __tablename__ = "users"

    id: Mapped[str] = mapped_column(String(64), primary_key=True)
    username: Mapped[str] = mapped_column(String(64), nullable=False, unique=True)
    # Email is optional but commonly used as a contact / recovery channel.
    email: Mapped[str | None] = mapped_column(String(254), nullable=True)
    # Argon2id hash (never the plaintext). Nullable for passkey-only accounts
    # in future revisions -- for MVP we require a password.
    password_hash: Mapped[str | None] = mapped_column(String(512), nullable=True)
    # TOTP secret is stored encrypted via the vault in M1/T7; for now the
    # column is reserved and the value defaults to NULL.
    totp_secret_encrypted: Mapped[str | None] = mapped_column(String(1024), nullable=True)
    totp_enabled: Mapped[bool] = mapped_column(
        # SQLite stores bool as INTEGER; SQLAlchemy handles the conversion.
        nullable=False,
        default=False,
    )
    role: Mapped[str] = mapped_column(String(16), nullable=False, default="owner")
    # disabled_at non-null => account is locked (audit must capture the reason).
    disabled_at: Mapped[dt.datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    # Last successful login (UTC). Used by the audit dashboard.
    last_login_at: Mapped[dt.datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    created_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )
    updated_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow, onupdate=_utcnow
    )

    sessions: Mapped[list[UserSession]] = relationship(
        back_populates="user", cascade="all, delete-orphan"
    )
    recovery_codes: Mapped[list[RecoveryCode]] = relationship(
        back_populates="user", cascade="all, delete-orphan"
    )

    __table_args__ = (
        CheckConstraint(
            "role IN ('owner', 'admin', 'operator', 'viewer')",
            name="ck_users_role",
        ),
    )


class UserSession(Base):
    """Server-side session record.

    The client only ever sees an opaque random token (HttpOnly cookie).
    We store the SHA-256 hash of the token in ``session_token_hash`` so a
    database compromise does NOT yield usable session cookies.
    """

    __tablename__ = "sessions"

    id: Mapped[str] = mapped_column(String(64), primary_key=True)
    user_id: Mapped[str] = mapped_column(String(64), ForeignKey("users.id"), nullable=False)
    session_token_hash: Mapped[str] = mapped_column(String(128), nullable=False, unique=True)
    # Hash of the double-submit CSRF cookie. Stored so we can rotate
    # / revoke the CSRF token independently of the session token.
    csrf_token_hash: Mapped[str | None] = mapped_column(String(128), nullable=True)
    ip_address: Mapped[str | None] = mapped_column(String(64), nullable=True)
    user_agent: Mapped[str | None] = mapped_column(String(512), nullable=True)
    expires_at: Mapped[dt.datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    revoked_at: Mapped[dt.datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )

    user: Mapped[User] = relationship(back_populates="sessions")

    __table_args__ = (
        Index("ix_sessions_user_id", "user_id"),
        Index("ix_sessions_expires_at", "expires_at"),
    )


class RecoveryCode(Base):
    """One-time recovery code used when the user loses TOTP / passkey."""

    __tablename__ = "recovery_codes"

    id: Mapped[str] = mapped_column(String(64), primary_key=True)
    user_id: Mapped[str] = mapped_column(String(64), ForeignKey("users.id"), nullable=False)
    # SHA-256 hash of the recovery code (plaintext is shown ONCE at creation).
    code_hash: Mapped[str] = mapped_column(String(128), nullable=False)
    used_at: Mapped[dt.datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )

    user: Mapped[User] = relationship(back_populates="recovery_codes")

    __table_args__ = (Index("ix_recovery_codes_user_id", "user_id"),)


# --------------------------------------------------------------------------- #
# Hosts
# --------------------------------------------------------------------------- #


HOST_AUTH_METHODS: frozenset[str] = frozenset({"password", "key", "key_with_passphrase"})
HOST_SUDO_MODES: frozenset[str] = frozenset({"root", "passwordless_sudo", "sudo_password"})
HOST_ENVIRONMENTS: frozenset[str] = frozenset({"experiment", "staging", "production"})


class Host(Base):
    """A target VPS. No agent runs on the host -- only SSH + shell.

    Sensitive fields (fingerprint, notes) live alongside encrypted
    credential rows in the vault; we never put decrypted values in
    the host row itself.
    """

    __tablename__ = "hosts"

    id: Mapped[str] = mapped_column(String(64), primary_key=True)
    name: Mapped[str] = mapped_column(String(64), nullable=False, unique=True)
    hostname_or_ip: Mapped[str] = mapped_column(String(255), nullable=False)
    ssh_port: Mapped[int] = mapped_column(Integer, nullable=False, default=22)
    username: Mapped[str] = mapped_column(String(64), nullable=False)
    auth_method: Mapped[str] = mapped_column(String(32), nullable=False)
    # Optional FK to a vault credential. Not enforced as a hard FK in
    # SQLite to allow hosts to exist before their creds are added.
    credential_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    sudo_mode: Mapped[str] = mapped_column(String(32), nullable=False, default="root")
    host_key_fingerprint: Mapped[str | None] = mapped_column(String(128), nullable=True)
    host_key_algorithm: Mapped[str | None] = mapped_column(String(16), nullable=True)
    os_family: Mapped[str | None] = mapped_column(String(32), nullable=True)
    os_name: Mapped[str | None] = mapped_column(String(64), nullable=True)
    os_version: Mapped[str | None] = mapped_column(String(64), nullable=True)
    package_manager: Mapped[str | None] = mapped_column(String(32), nullable=True)
    arch: Mapped[str | None] = mapped_column(String(16), nullable=True)
    cpu_cores: Mapped[int | None] = mapped_column(Integer, nullable=True)
    ram_mb: Mapped[int | None] = mapped_column(Integer, nullable=True)
    disk_total_mb: Mapped[int | None] = mapped_column(Integer, nullable=True)
    provider: Mapped[str | None] = mapped_column(String(64), nullable=True)
    region: Mapped[str | None] = mapped_column(String(64), nullable=True)
    environment: Mapped[str] = mapped_column(String(16), nullable=False, default="experiment")
    risk_level: Mapped[str | None] = mapped_column(String(16), nullable=True)
    tags: Mapped[list] = mapped_column(JSON, nullable=False, default=list)
    notes: Mapped[str] = mapped_column(String(2048), nullable=False, default="")
    last_seen_at: Mapped[dt.datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    disabled_at: Mapped[dt.datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )
    updated_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow, onupdate=_utcnow
    )

    __table_args__ = (
        CheckConstraint(
            "auth_method IN ('password', 'key', 'key_with_passphrase')",
            name="ck_hosts_auth_method",
        ),
        CheckConstraint(
            "sudo_mode IN ('root', 'passwordless_sudo', 'sudo_password')",
            name="ck_hosts_sudo_mode",
        ),
        CheckConstraint(
            "environment IN ('experiment', 'staging', 'production')",
            name="ck_hosts_environment",
        ),
        Index("ix_hosts_tags", "tags"),
        Index("ix_hosts_environment", "environment"),
    )


# --------------------------------------------------------------------------- #
# Jobs
# --------------------------------------------------------------------------- #


JOB_STATUSES: frozenset[str] = frozenset(
    {"queued", "running", "success", "failed", "cancelled", "denied"}
)
JOB_APPROVAL_STATUSES: frozenset[str] = frozenset({"not_required", "pending", "approved", "denied"})
JOB_LOG_STREAMS: frozenset[str] = frozenset({"stdout", "stderr", "system"})


class Job(Base):
    """A queued or completed remote-execution job."""

    __tablename__ = "jobs"

    id: Mapped[str] = mapped_column(String(64), primary_key=True)
    host_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    recipe_name: Mapped[str | None] = mapped_column(String(128), nullable=True)
    command_summary: Mapped[str] = mapped_column(String(2048), nullable=False)
    requested_by_user_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    status: Mapped[str] = mapped_column(String(16), nullable=False, default="queued")
    risk_level: Mapped[str | None] = mapped_column(String(16), nullable=True)
    approval_status: Mapped[str] = mapped_column(String(16), nullable=False, default="not_required")
    approval_requested_at: Mapped[dt.datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    approved_by_user_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    approved_at: Mapped[dt.datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    started_at: Mapped[dt.datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    finished_at: Mapped[dt.datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    timeout_seconds: Mapped[int] = mapped_column(Integer, nullable=False, default=300)
    exit_code: Mapped[int | None] = mapped_column(Integer, nullable=True)
    error_summary_redacted: Mapped[str | None] = mapped_column(String(2048), nullable=True)
    idempotency_key: Mapped[str | None] = mapped_column(String(128), nullable=True)
    created_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )
    updated_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow, onupdate=_utcnow
    )

    steps: Mapped[list[JobStep]] = relationship(back_populates="job", cascade="all, delete-orphan")
    logs: Mapped[list[JobLog]] = relationship(
        back_populates="job",
        cascade="all, delete-orphan",
        order_by="JobLog.id.asc()",
    )

    __table_args__ = (
        CheckConstraint(
            "status IN ('queued', 'running', 'success', 'failed', 'cancelled', 'denied')",
            name="ck_jobs_status",
        ),
        CheckConstraint(
            "approval_status IN ('not_required', 'pending', 'approved', 'denied')",
            name="ck_jobs_approval_status",
        ),
        Index("ix_jobs_status", "status"),
        Index("ix_jobs_host_id", "host_id"),
        Index("ix_jobs_created_at", "created_at"),
    )


class JobStep(Base):
    """One step within a (recipe) job."""

    __tablename__ = "job_steps"

    id: Mapped[str] = mapped_column(String(64), primary_key=True)
    job_id: Mapped[str] = mapped_column(String(64), ForeignKey("jobs.id"), nullable=False)
    step_index: Mapped[int] = mapped_column(Integer, nullable=False)
    name: Mapped[str] = mapped_column(String(128), nullable=False)
    status: Mapped[str] = mapped_column(String(16), nullable=False, default="queued")
    started_at: Mapped[dt.datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    finished_at: Mapped[dt.datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    exit_code: Mapped[int | None] = mapped_column(Integer, nullable=True)
    error_summary_redacted: Mapped[str | None] = mapped_column(String(2048), nullable=True)

    job: Mapped[Job] = relationship(back_populates="steps")

    __table_args__ = (
        UniqueConstraint("job_id", "step_index", name="uq_job_steps_index"),
        CheckConstraint(
            "status IN ('queued', 'running', 'success', 'failed', 'cancelled', 'skipped')",
            name="ck_job_steps_status",
        ),
    )


class JobLog(Base):
    """A single log line emitted by a running job.

    Only redacted text is stored. line_hash is the SHA-256 of the
    redacted line, useful for tamper detection in audit reviews.
    """

    __tablename__ = "job_logs"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    job_id: Mapped[str] = mapped_column(String(64), ForeignKey("jobs.id"), nullable=False)
    step_id: Mapped[str | None] = mapped_column(
        String(64), ForeignKey("job_steps.id"), nullable=True
    )
    stream: Mapped[str] = mapped_column(String(16), nullable=False)
    line_redacted: Mapped[str] = mapped_column(String(4096), nullable=False)
    line_hash: Mapped[str | None] = mapped_column(String(128), nullable=True)
    timestamp: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )

    job: Mapped[Job] = relationship(back_populates="logs")

    __table_args__ = (
        CheckConstraint(
            "stream IN ('stdout', 'stderr', 'system')",
            name="ck_job_logs_stream",
        ),
        Index("ix_job_logs_job_id", "job_id"),
    )


class Agent(Base):
    """An AI Agent connection registry in VMAN (Agent Bridge)."""

    __tablename__ = "agents"

    id: Mapped[str] = mapped_column(String(64), primary_key=True)
    name: Mapped[str] = mapped_column(String(128), nullable=False)
    status: Mapped[str] = mapped_column(String(32), nullable=False)
    dns_status: Mapped[str] = mapped_column(String(16), nullable=False)
    domains: Mapped[list[str]] = mapped_column(JSON, nullable=False, default=list)
    last_seen_at: Mapped[dt.datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )
    updated_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow, onupdate=_utcnow
    )

    __table_args__ = (
        CheckConstraint(
            "status IN ('active', 'setup_required', 'offline')",
            name="ck_agents_status",
        ),
        CheckConstraint(
            "dns_status IN ('on', 'off')",
            name="ck_agents_dns_status",
        ),
    )


__all__ = [
    "ACTOR_TYPES",
    "AuditEvent",
    "CREDENTIAL_KINDS",
    "Credential",
    "EncryptionKey",
    "HOST_AUTH_METHODS",
    "HOST_ENVIRONMENTS",
    "HOST_SUDO_MODES",
    "Host",
    "JOB_APPROVAL_STATUSES",
    "JOB_LOG_STREAMS",
    "JOB_STATUSES",
    "Job",
    "JobLog",
    "JobStep",
    "RecoveryCode",
    "USER_ROLES",
    "User",
    "UserSession",
    "Agent",
]
